version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bot_service/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  bot_service:
    build: ./bot_service
    container_name: bot_service
    restart: always
    depends_on:
      - db
    env_file:
      - ./bot_service/.env
    volumes:
      - ./bot_service:/app
    ports:
      - "8000:8000"

  connector_service:
    build: ./connector_service
    container_name: connector_service
    restart: always
    depends_on:
      - bot_service
    env_file:
      - ./connector_service/.env
    ports:
      - "3000:3000"
    command: ["node", "dist/connector.js"] 
volumes:
  postgres_data:
